/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package formatter

import com.sun.xml.internal.messaging.saaj.util.ByteOutputStream
import java.io.File
import java.io.OutputStream
import kotlin.test.Test
import kotlin.test.assertEquals

class TableBuilderTest {

    private val result =
        "Test   \ttest\ttestet\t\n" +
                "ter    \tte  \t\n" +
                "123.123\t12.0\ttest  \t123\t\n"

    private val testFiles = File("testFiles").apply {
        mkdirs()
    }

    private fun borderlessTest(stream: OutputStream) {
        val tableBuilder = TableBuilder.create(stream)
        tableBuilder.add("Test", "test", "testet")
        tableBuilder.add("ter", "te")
        tableBuilder.add(123, 13, 123)
        tableBuilder.add(123.123, 12.0, "test", 123)
        tableBuilder.removeAt(2)
        tableBuilder.write()
    }

    @Test fun borderlessByteStreamTest() {
        val stream = ByteOutputStream()
        borderlessTest(stream)
        stream.flush()
        assertEquals(result, stream.toString())
    }

    @Test fun borderlessFileStreamTest() {
        val file = File(testFiles, "borderlessFileStreamTest.txt")
        file.mkdirs()
        file.createNewFile()

        val stream = file.outputStream()
        borderlessTest(stream)
        stream.flush()
        stream.close()

        val fileInput = file.readLines().joinToString("\n").plus("\n")

        assertEquals(fileInput, result)
    }
}
